x-postgres-env: &postgres-env
  POSTGRES_USER: shortener_user
  POSTGRES_PASSWORD: super_secret_password
  POSTGRES_DB: shortener_db

services:
  postgres:
    image: postgres:18.3-alpine3.23
    container_name: shortener-postgres
    environment:
      <<: *postgres-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d shortener_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
